# Generated by Django 5.2.8 on 2025-12-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(default='Masculin', max_length=20)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('wilaya', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=9, unique=True)),
                ('level', models.CharField(max_length=10)),
                ('departement', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
